### ISSUE TITLE
Setup Visual Testing

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/nuxt-client#108]
To prevent ugly UI changes to be merged, we wan't a tool that let's us review visual changes and block merges until a UI review was given.

**Comment by adrianjost** [comment]
# [percy.io](https://percy.io)
- + schöne, intuitive Oberfläche für Reviews
- + Github Integration, welche das mergen blockt, bis ein Review vorhanden ist
- - ab >10 Developern wird es teuer ([pricing](https://percy.io/pricing))

**Comment by janrenz** [comment]
Das sollte nachher hand in Hand mit den Arbeiten in den Integrationstests gehen, da haben wir ja bereits Visuelles regressions testing ...

**Comment by adrianjost** [comment]
Ahhh, das wusste ich noch gar nicht. 
Welches Tool benutzen wir dort?

**Comment by adrianjost** [comment]
implemented with jest
