### ISSUE TITLE
Remove Google Fonts from Storybook

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/nuxt-client#109]
Storybook is currently loading fonts from fonts.google.com. This should be replaced with a local copy to remove all unnecessary external calls.

**Comment by ChrisWeissmann** [comment]
Not sure what best practice is for this. 
Using the package https://www.npmjs.com/package/google-fonts-webpack-plugin 
Or import them to the project as a ttf file?

**Comment by adrianjost** [comment]
I would go with downloaded, local versions. We do this in all other repositories as well.
There shouldn't be any need for updates of the font in the furture so version management like npm is not an huge improvement.

**Comment by adrianjost** [comment]
done
