### ISSUE TITLE
Setup Accessibility Testing

### ISSUE THREAD

**Issue by dominikbruechner** [schul-cloud/nuxt-client#112]
https://cruft.io/posts/automated-accessibility-testing-node-travis-ci-pa11y/

**Comment by adrianjost** [comment]
I still like the idea. We already have the Accesslint bot. As I found out just now, he has some problems with vues template syntax: https://github.com/schul-cloud/nuxt-client/pull/136#pullrequestreview-220461568
We should definetly check if your suggestions supports this case better.

**Comment by adrianjost** [comment]
I will close this for now. I still think this is a good idea, but we have the Accesslint bot already and it's working ok. We shouldn't have that many accessibility flaws as log as we are reusing our components and variables. Feel free to reopen.
