### ISSUE TITLE
Improve parallel output of `yarn dev`

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/nuxt-client#117]
it would be nice to have the ports of the running services logged to the console. Currently the output of the three services gets mixed and is unreadable.

Pull where this problem was discovered:
https://github.com/schul-cloud/nuxt-client/pull/111

**Comment by adrianjost** [comment]
Maybe the `--aggregate-output` flag fixes the problem. 
Docs: https://github.com/mysticatea/npm-run-all/blob/5017a8879af4afead7a87d378ac0cca5393e7e43/docs/run-p.md

**Comment by adrianjost** [comment]
Update: `--aggregate-output` macht nur den build und lint output bei parallelität schöner, mit den dev-skripten kommt es aber nicht klar, da diese nie fertig sind und er somit nie output bei 2/3 Skripten ausgibt.

**Comment by ChrisWeissmann** [comment]
Fixed in #120
