### ISSUE TITLE
Configure "Mergable" Bot

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/nuxt-client#121]
For more detailed merge blocking we have the mergable bot enabled. This can do the same thing as the WIP-Bot but can be configured and is free forever.

Options: https://github.com/jusx/mergeable#configuration

**Comment by adrianjost** [comment]
@dominikbruechner Ticket https://ticketsystem.schul-cloud.org/browse/VUE-39 könnte hier mit abgeschlossen werden.

**Comment by adrianjost** [comment]
Was soll der Bot mind. unterstützen (gerne erweitern):
- Check auf WIP in den Labels, Title, Description
- Titel & Description müssen vorhanden sein

**Comment by adrianjost** [comment]
Im bestehenden Client gibt es für diesen Problem den Bot "PullApprove":
Config: https://github.com/schul-cloud/schulcloud-server/blob/master/.pullapprove.yml

**Comment by adrianjost** [comment]
Noch besser, als fertiger Github Bot der nur noch konfiguriert werden muss: https://mergify.io

**Comment by ChrisWeissmann** [comment]
Kann das hier dann geschlossen werden?

**Comment by adrianjost** [comment]
@ChrisWeissmann Noch nicht. Erst wenn #149 durch ist.
