### ISSUE TITLE
Discuss Concept for State Style of Components.

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/nuxt-client#127]
Der `BaseButton` bietet viele Klassen an (`.is-small`, `.is-secondary`, ...) welche für den Entwickler nicht direkt sichtbar sind. Hier sollte ein konzept überlegt werden, wie wir diese Info besser Kapseln können und gleichzeitig nach außen sichtbar machen.

Eine Idee: Extra Komponente für Submit, Cancel... um events usw. automatisch zu regeln.

**Comment by adrianjost** [comment]
Brainstrorming mit @ChrisWeissmann 
Idee:
jede Komponente mit verschiedenen styles hat eine property `design` welche verschiedene textwerte annimmt und die Komponente selbst kümmert sich um das gesamte styling der Komponente.

Usage:
`<BaseButton design="textbutton primary" >Button</BaseButton> `

Komponente
```js
export default = {
props: {
  design: {
    type: String,
    validator: (design) => { ["textbutton primary"].includes(design) }
  }
}
}
```

**Comment by ChrisWeissmann** [comment]
Ich würde das mal in die docs packen. Bitte nochmal melden falls es andere Vorschläge gibt
