### ISSUE TITLE
add postCss for autoprefix plugin

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/nuxt-client#129]
👆

**Comment by adrianjost** [comment]
I wasn't able to figur out how to do that, so I need some help here @rodebert / @ChrisWeissmann .

**Comment by ChrisWeissmann** [comment]
I looked into it a bit. What would the perfect test case be to check if it works?

**Comment by adrianjost** [comment]
I would say add something that needs to be prefixed, like `@keyframe`, to the css anywhere. Then run `yarn build:nuxt` and search in the `dist/nuxt` folder (vscode can do that) for the prefixed version (like `@-webkit-keyframe` for keyframes)

**Comment by ChrisWeissmann** [comment]
Followed instructions on here: [nuxtjs.org](https://nuxtjs.org/faq/postcss-plugins/)
I think we can delete the .postcssrs.js file or does it serve a purpose?
