### ISSUE TITLE
Discuss Merge vs Squash on Pull Requests

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/nuxt-client#135]
Mit Squash wird immer die Person geblamed welche den Pull gemerged hat (aktuell meist ich). Dies widerspricht dem Sinn von Git Blame und wir sollten diskutieren ob es alternativen gibt.

Zu Beachten ist, dass der Revert eines Pulls weiterhin einfach sein sollte und daher nicht alle Commits 1:1 in den master übernommen werden sollten.

**Comment by ChrisWeissmann** [comment]
Man kann ja auch selbst local seine commist squaschen. Alles was man selbst getan hat in einen commit zusammen fassen und mit einer anständigen message versehen. Anschließend sind es ja nicht mehr so viele commits und man könnte sie in die Master history mit aufnehmen.
Wie man das als Regel durch setzt weis ich nicht 😦

**Comment by adrianjost** [comment]
Nach dem lesen der Github Erklärung ([link](https://help.github.com/en/articles/about-merge-methods-on-github)) erscheint mir das einfache "Create a merge commit" am sinnvollsten. Es behält den Autor der einzelnen Zeilen bei und erzeugt gleichzeitig nur einen einfachen (merge) Commit. Es sollte also weiterhin einfach zu reverten sein.

Die Idee von dir @ChrisWeissmann finde ich zu kompliziert durchzusetzen, auch wenn sie sicherlich funktionieren würde.
Was haltet Ihr davon, erst einmal auf den einfachen "merge-commit" zu wechseln und zu sehen ob es irgendwelche Probleme gibt (vermute ich jetzt nicht)?

**Comment by adrianjost** [comment]
Die Option "Rebase and Merge" erscheint mir 
a) zu kompliziert
b) ist es wohl riskant, da es wohl leicht passieren kann, dass Arbeit aus verschiedenen Branches "verloren" geht, wenn beim rebase etwas nicht klappt oder falsch gemacht wurde.

**Comment by adrianjost** [comment]
**create a merge commit**
![](https://help.github.com/assets/images/help/pull_requests/standard-merge-commit-diagram.png)
**squash and merge**
![](https://help.github.com/assets/images/help/pull_requests/commit-squashing-diagram.png)

**Comment by ChrisWeissmann** [comment]
> Was haltet Ihr davon, erst einmal auf den einfachen "merge-commit" zu wechseln und zu sehen ob es irgendwelche Probleme gibt (vermute ich jetzt nicht)?

Wäre ich mit anboard
