### ISSUE TITLE
Base components TODOs

### ISSUE THREAD

**Issue by ChrisWeissmann** [schul-cloud/nuxt-client#15]
Please add your name behind components you are developing and link the branch

# Following should be created as **base components** :
- [x] BaseLink
- [x] BaseInput
  - [x] type="date", ... (with DatePicker Component) [Domi]
  - [x] Switch
  - [x] hidden
  - [x] radio
- [x] BaseSelect [Domi]
  - [x] like normal html select
  - [x] tags/pills design? (Multiselect) [Domi]
- [x] BaseCard
- [x] BaseVideo [Angelika]
- [x] BaseAudio [Angelika]
- [x] BaseIcon
- [x] BaseModal

# Additionaly the following components should be also available:
- [x] Breadcrumb [Angelika]
- [x] Tabs [Chris]
- [x] Dropdown Menüs [Angelika]
- [x] Quote-Tag
- [x] Headline Classes
- [x] Collapsible
- [x] ProfileImage
- [ ] Filter (Feathers Filter Module) [Adrian]
- [ ] FAB (Floating Action Button) [ Adrian]
- [x] Tabelle
- [x] progress bar
- [x] Toasts (sind keine echte Komponente)

## Further todo's:
- [x] Theming (Michael)

**Comment by dominikbruechner** [comment]
BaseInput type=date will be done by me

**Comment by adrianjost** [comment]
Issues found:
- [ ] We should discuss, what components are considered `BaseComponents` and which are just normal Components. For example: I don't think `BaseProgressbar` isn't really a BaseComponent, cause I don't think it will be used that often. **We should create our own definition for what we count as BaseComponents, document this and move/rename our components accordingly**
