### ISSUE TITLE
Improve Docs Search

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/nuxt-client#165]
Vuepress offers algolia integration. It's free to use and easy to integrate.

1. We just need to apply here:
https://community.algolia.com/docsearch/
1. And follow this vuepress docs entry:
https://vuepress.vuejs.org/default-theme-config/#algolia-search

**Comment by ChrisWeissmann** [comment]
Applied and waiting for API key.

**Comment by ChrisWeissmann** [comment]
Contacted them via discord. Apperently we fell out of the que. But are back in now :) Should be only a matter of time

**Comment by ChrisWeissmann** [comment]
Apperently HPI thought the email with the key was spam. Found the key in the spam folder today and gave it a try successfully.
