### ISSUE TITLE
use DayJS instead of Moment.JS

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/nuxt-client#173]
It's **a lot** smaller!
https://github.com/iamkun/dayjs

**Comment by ChrisWeissmann** [comment]
Looks good!
Supports I18n!
Here is the doc about how to add the support: https://github.com/iamkun/dayjs/blob/dev/docs/en/I18n.md

**Comment by ChrisWeissmann** [comment]
@adrianjost  can this be closed then? seems like you mentioned this in the PR but I can't find the reference.

**Comment by adrianjost** [comment]
No, it isn't implemented yet. We are still using mobile. This ticket was created as a future todo
