### ISSUE TITLE
Create Course, MultiSelects "broken"

### ISSUE THREAD

**Issue by dominikbruechner** [schul-cloud/nuxt-client#188]
All the MultiSelects in Create Course don't get any more data. Probs because of changes to the Component.

**Comment by adrianjost** [comment]
Will be fixed in #187 I guess.
https://github.com/schul-cloud/nuxt-client/pull/187/files#diff-3d295a926e5a35a7894df671047b5244R62

**Comment by ChrisWeissmann** [comment]
Seems fixed in the PR #187 
<img width="936" alt="Bildschirmfoto 2019-05-27 um 11 54 14" src="https://user-images.githubusercontent.com/2805418/58412190-38dcc700-8076-11e9-8338-29ffbbc15ded.png">


I will close the issue
