### ISSUE TITLE
Fix mergify config

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/nuxt-client#216]
I completed a survey about mergify experiences and complained about the label removable issue we have on some pull requests.
I got the following response: ...
We should try this. I just don't had time for it now.

I see. I think the issue is with your rule:

  - name: automatic merging when label is set
    conditions:
      - label!=WIP
      - label!=waiting
      - label~=ready to merge
      - status-success~=Travis CI
      - status-success=Mergeable
      - status-success=codecov/project
    actions:
      merge:
        method: merge
        strict: true
      label:
        remove:
          - ready to merge

The issue is that when Mergify receives your label event, this matches,
so it does:
- merge, meaning updating the PR (strict is true), which is what it does.
  Your status-success is not matching anymore, so Mergify stops here.
- remove the label.

And then it can't merged since the rules does not match.

You should write something along these rules instead:

  - name: automatic merging when label is set
    conditions:
      - label!=WIP
      - label!=waiting
      - label=ready to merge
      - status-success~=Travis CI
      - status-success=Mergeable
      - status-success=codecov/project
    actions:
      merge:
        method: merge
        strict: true
  - name: remove ready to merge when merged
    conditions:
      - merged
      - label=ready to merge
    actions:
      label:
        remove:
          - ready to merge

**Comment by ChrisWeissmann** [comment]
Opened a PR for this. Not sure how it could be tested beforehand, so trusting the feedback for now...

**Comment by adrianjost** [comment]
You simply can't ;) let's merge it and continue investigating it

**Comment by ChrisWeissmann** [comment]
Seems to be working. I will close the issue. Feel free to reopen if it was a mistake
