### ISSUE TITLE
add tool for Coverage review

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/nuxt-client#24]
Damit wir auch wirklich "gezwungen" sind Tests zu schreiben (zumindest für die BaseComponents) schlage ich vor ein Tool wie 
https://codecov.io/ oder https://coveralls.io einzurichten, welches Pull Requests entsprechend Blockt, wenn die Code Coverage zu sehr sinkt.

**Comment by janrenz** [comment]
finde ich gut, müssen nur mal schauen wie wir das dann mit den Tests in dem externen Repo hinbekommen.. notfalls müssen die halt doch hier ins Repo

**Comment by adrianjost** [comment]
@janrenz hast du eine Präferenz für eines der Tools? Im Server benutzen wir soweit ich weiß ja schon https://codecov.io

**Comment by janrenz** [comment]
Ne, hab da keine besondere Erfahrung / Präferenz. Gerne das Probieren was schon verwendet wird

**Comment by adrianjost** [comment]
@janrenz ich würde gerne die Integration von https://codecov.io ausprobieren wollen. Kannst du das zu dem Repo hinzufügen? (Können nur Administratoren der Organisation)
