### ISSUE TITLE
Display nav  based on users permissions

### ISSUE THREAD

**Issue by janrenz** [schul-cloud/nuxt-client#3]
We just need to check the display, everything else should be handled in the api

**Comment by adrianjost** [comment]
Wie wäre es eine Schnittstelle im Serve a la _Menüpunkte_ zu definieren?

**Comment by smyth64** [comment]
Könnten wir über asyncdata lösen. Dann wäre das Menü auf jeden Fall da, bevor der Dom gerendert wird.

**Comment by smyth64** [comment]
Der Client müsste aber trotzdem die routes kennen, sonst wird es kompliziert

**Comment by adrianjost** [comment]
Klingt gut, also im Server erstellen wir eine route a la `menüpunkte` welche anhand der Berechtigungen eines Nutzers die Menüpunkte zurückgibt. Im Client könnten wir dann ein mapping dieser auf routen machen. Dann muss der Server auch nichts über die genauen Routen im Frontend wissen sondern kann eher auf Feature ebene arbeiten.
Oder ist das dann zu viel abstraktion?

**Comment by janrenz** [comment]
Warum nicht an die Menüpunkte in frontend die benötigtem Permissions hängen und dort filtern. Welche es gibt ist ja nicht privat..

**Comment by smyth64** [comment]
Ja bin ich auch dafür. Ich seh da keinen Vorteil, es vom Backend zu holen.

Jan Renz <notifications@github.com> schrieb am Mi. 27. Feb. 2019 um 18:37:

**Comment by smyth64** [comment]
Die permissions bzw roles kann man ja einfach vom Store holen. Stehen ja im
User object.

Smith64FX <smith64fx@gmail.com> schrieb am Mi. 27. Feb. 2019 um 18:43:

**Comment by adrianjost** [comment]
Hast eigentlich Recht. Logik einfach im Store Kapseln und die Trennung Server/Client bleibt erhalten. Überzeugt

**Comment by adrianjost** [comment]
haben wir
