### ISSUE TITLE
Accesslint zur Accessibility prüfung

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/nuxt-client#34]
Ich habe diesen coolen Bot gefunden:
https://github.com/marketplace/accesslint

Ansich könnten wir das aber auch über eslint/stylelint glaube ganz gut abdecken wenn wir wollen. Können wir mal diskutieren, wie und ob wir solche accessibility tests einbauen wollen

**Comment by ChrisWeissmann** [comment]
Bei storybook ist auch ein addon eingebunden das mit anzeigt wie es um die accessibility steht. Trotzdem gut nen test mit drin zu haben.

**Comment by adrianjost** [comment]
Das mit Storybook habe ich auch schon gesehen und finde ich super. Ich wäre trotzdem noch für irgend eine Art Tool, welches grundlegende Accessibility Sachen erzwingt, damit nicht versehentlich schlechter Code gemerged wird. Die Einbindung in Storybook ist super zum Entwickeln!

**Comment by ChrisWeissmann** [comment]
Kann denk ich geschlossen werden da @janrenz Accesslint aktiviert hat.
