### ISSUE TITLE
Bulldozer (Bot) für automatisches Mergen, wenn möglich

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/nuxt-client#39]
Ich habe diesen coolen Bot gefunden:
https://github.com/palantir/bulldozer
damit könnten wir automatisch mergen, sobald alles approved ist und die tests durchlaufen (wenn travis mal wieder länger braucht).
Wenn es richtig konfiguriert ist könnte uns das eineiges an Arbeit abnehmen, da man nicht erst auf "update from master" klicken muss, 5min später wiederkommen muss um versuchen zu mergen und dann festzustellen, dass doch schon wieder was anderes im master gelandet ist.

**Comment by adrianjost** [comment]
Alternative: https://github.com/depop/github-merge-bot

**Comment by adrianjost** [comment]
Ich habe etwas noch besseres gefunden: https://mergify.io/
Funktioniert direkt als Github app und muss nur konfiguriert werden. Ich evaluiere es gerade in einem privaten Projekt. Automatisches mergen, sobald alle Requirements erfüllt sind funktioniert schonmal, ich teste noch ob er auch automatisch "update from master" ausführen kann.

**Comment by adrianjost** [comment]
@schul-cloud/coredevs Ich habe eine Anfrage gestellt, dass der Bot für dieses Repo aktiviert wird.

**Comment by malcm** [comment]
@schul-cloud/coredevs Wollt ihr das bei nuxt haben? ich denke für den produktiven Client und Server kann das unter Umständen zu Problemen kommen, wenn ein Feature drin ist mit dem keiner direkt gerechnet hat.

**Comment by adrianjost** [comment]
Ja, das ganze würde auch hinter einem label laufen, sodass der Bot erst anspringt wenn bspw. das Label "merge branch" gesetzt wurde.
Das würde dann einiges an Zeit sparen, da man nicht regelmäßig gucken muss, ob endlich alle Tests durchgelaufen sind um zu mergen und ggf. erst nochmal vom master updaten muss und sich das Spiel wiederholt.

**Comment by malcm** [comment]
@adrianjost Klingt gut. Sollte dann aber noch in der readme beschrieben werden.

**Comment by adrianjost** [comment]
@malcm Definitiv! Kommt dann alles in unsere docs, pull templates usw..
Vielen Dank fürs aktivieren
