### ISSUE TITLE
Storybook deployment is broken

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/nuxt-client#61]
Currently the storybook isn't reachable (for over a week now):

https://storybook.test.schul-cloud.org/

![image](https://user-images.githubusercontent.com/22987140/53482224-0d4e3e80-3a7f-11e9-9e0d-4c818de3e5b7.png)

Build details can be found here: https://vuepress.test.schul-cloud.org/0-GettingStarted/1-Build.html

**Comment by ChrisWeissmann** [comment]
@dominikbruechner please close this issue if you fixed it. :)

**Comment by dominikbruechner** [comment]
fixed with https://github.com/schul-cloud/nuxt-client/pull/62
